# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of Node.js

name: Node.js CI

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install additional tools
      run: |
        npm install rollup
        npm install @swc/core

    - name: Build the project
      run: npm run build --if-present
